--------------------------------------------------------
--  File created - Thursday-November-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View XXFT_CHRM_END_INV_RPT_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "APPS"."XXFT_CHRM_END_INV_RPT_V" ("CUSTOMER", "CUSTOMER_NUMBER", "ORDER_TYPE", "DROP_SHIP", "ORDER_NUMBER", "ORDER_SHIP_DATE", "CUSTOMER_PO", "INVOICE_NUMBER", "INVOICE_DATE", "SKU", "QTY", "SERIAL_NUMBER", "CONTRACT_NUMBER", "NET_PRICE", "EXTENDED_NET_PRICE", "LIST_PRICE", "EXTENDED_LIST_PRICE", "UNIT_COST", "EXTENDED_COST", "OPPORTUNITY", "SPR", "END_USER", "POS_INV_DATE", "SEQ_NUMBER") AS 
  SELECT
  /*+ PARALLEL(RAC,1000)  PARALLEL(XR,1000) */
  XR.CUSTOMER_NAME Customer,
  /* ITS#543628*/
  XR.BILL_TO_CUSTOMER_NUMBER Customer_Number,
  XR.ORDER_TYPE Order_Type,
  (
    SELECT DECODE(NVL(oh.attribute5,'N'),'Y','N','Y')
    FROM oe_order_headers_all oh
    WHERE XR.CUSTOMER_ID  = oh.SOLD_TO_ORG_ID
    AND XR.SALES_ORDER    = oh.ORDER_NUMBER
    AND XR.SALES_ORDER_ID = oh.HEADER_ID
  )
  Drop_Ship,
  --'N' Drop_Ship,
  TO_CHAR(XR.SALES_ORDER) Order_Number,
  XR.SHIP_DATE Order_Ship_Date,
  XR.PO_NUM Customer_PO,
  RA.TRX_NUMBER Invoice_Number,
  RA.TRX_DATE Invoice_Date,
  XR.ITEM_NUMBER SKU,
  XR.QUANTITY_ORDERED Qty,
  xr.attribute33 Serial_Number,
  xr.attribute45 Contract_Number,
  xr.UNIT_SELL_PRICE Net_Price,
  ROUND(XR.QUANTITY_ORDERED * xr.UNIT_SELL_PRICE,2) Extended_Net_Price,
  XR.UNIT_LIST_PRICE List_Price,
  ROUND(XR.QUANTITY_ORDERED * xr.UNIT_SELL_PRICE,2) Extended_List_Price,
  ROUND(XR.COST_AMOUNT,4) Unit_Cost,
  ROUND(XR.QUANTITY_ORDERED * ROUND(XR.COST_AMOUNT,4),2) Extended_Cost,
  NULL Opportunity,
  xr.attribute34 SPR,
  xr.attribute8 End_User,
  NULL POS_INV_DATE,
  TO_CHAR(XR.SALES_ORDER_LINE_BATCH_ID) SEQ_NUMBER
FROM XXFT.XXFT_RPRO_ORDER_DETAILS XR,
  (
    SELECT RAC.TRX_NUMBER,
      RAC.TRX_DATE,
      RAL.INTERFACE_LINE_ATTRIBUTE1,
      RAL.INTERFACE_LINE_ATTRIBUTE6
    FROM RA_CUSTOMER_TRX_ALL RAC,
      RA_CUSTOMER_TRX_LINES_ALL RAL
    WHERE RAC.CUSTOMER_TRX_ID = RAL.CUSTOMER_TRX_ID
  )
  RA
WHERE XR.order_line_status          = 'CLOSED'
AND TO_CHAR(XR.SALES_ORDER)         = RA.INTERFACE_LINE_ATTRIBUTE1
AND TO_CHAR(XR.SALES_ORDER_LINE_ID )= RA.INTERFACE_LINE_ATTRIBUTE6
  --and XR.SALES_ORDER_LINE_ID = ol.LINE_ID
--AND XR.SALES_ORDER_LINE_BATCH_ID = 943509
AND XR.PARENT_LINE               = 'Y'
and XR.ATTRIBUTE37 = 'P' --ITS#575976 and 599807
AND NOT EXISTS
  (
    SELECT 'Y'
    FROM OZF_RESALE_LINES_INT_ALL
    WHERE LINE_ATTRIBUTE15 NOT LIKE '%-H'
    AND quantity        > 0
    AND LINE_ATTRIBUTE15=TO_CHAR(XR.SALES_ORDER_LINE_BATCH_ID)
  )
AND NOT EXISTS
  (
    SELECT 'Y'
    FROM OZF_RESALE_LINES_INT_ALL
    WHERE LINE_ATTRIBUTE15 NOT LIKE '%-H'
    AND line_attribute14 IS NULL
    AND LINE_ATTRIBUTE15  = XR.po_num
    AND item_number       = 'COTERM'
  )
AND NOT EXISTS
  (
    SELECT RPRO.SALES_ORDER_LINE_BATCH_ID
    FROM XXFT.XXFT_RPRO_INVOICE_DETAILS RPRO,
      ra_customer_trx_all RA ,
      FND_LOOKUP_VALUES_VL VL,
      RA_CUST_TRX_TYPES_ALL RT
    WHERE RPRO.TRAN_TYPE               = 'CM'
    AND RA.CUSTOMER_TRX_ID             = RPRO.INVOICE_ID
    AND RT.CUST_TRX_TYPE_ID            = RA.CUST_TRX_TYPE_ID
    AND RT.TYPE                        = 'CM'
    AND RPRO.SALES_ORDER_LINE_BATCH_ID = XR.SALES_ORDER_LINE_BATCH_ID
    AND VL.lookup_type                 = 'CREDIT_MEMO_REASON'
    AND VL.ATTRIBUTE_CATEGORY          = 'CREDIT_MEMO_REASON'
    AND VL.VIEW_APPLICATION_ID         =222
    AND VL.ATTRIBUTE1                  = 'Y'
    AND RA.REASON_CODE                 = VL.LOOKUP_CODE
  )
/*XR.SALES_ORDER_LINE_BATCH_ID not in
(SELECT RPRO.SALES_ORDER_LINE_BATCH_ID
FROM XXFT.XXFT_RPRO_INVOICE_DETAILS RPRO,
  ra_customer_trx_all RA ,
  RA_CUST_TRX_TYPES_ALL RT
WHERE RPRO.TRAN_TYPE   = 'CM'
AND RA.CUSTOMER_TRX_ID = RPRO.INVOICE_ID
AND RT.CUST_TRX_TYPE_ID = RA.CUST_TRX_TYPE_ID
AND RPRO.SALES_ORDER_LINE_BATCH_ID is not null
AND RPRO.sales_order is not null
and RT.NAME <> 'FTNT SPR Claim CM') */
UNION ALL/* ITS#543628*/
SELECT /*+ PARALLEL(OZF,1000) */HP.PARTY_NAME Customer,
  HZC.ACCOUNT_NUMBER Customer_Number,
  NULL Order_Type,
  NULL Drop_Ship, -- This would be a DFF need info from OTC team
  OZF.ATTRIBUTE3 Order_Number,
  to_date(NULL) Order_Ship_Date,
  OZF.ATTRIBUTE5 Customer_PO,
  OZF.ATTRIBUTE1 Invoice_Number,
  OZF.TRANSACTION_DATE Invoice_Date,
  MTL.SEGMENT1 SKU,
  OZF.QUANTITY Qty,
  OZF.ATTRIBUTE8 Serial_Number,
  OZF.ATTRIBUTE9 Contract_Number,
  to_number(OZF.ATTRIBUTE10) Net_Price,
  ROUND(to_number(OZF.ATTRIBUTE10) * OZF.QUANTITY,2) Extended_Net_Price,
  NULL List_Price,
  NULL Extended_List_Price,
  NULL Unit_Cost,
  NULL Extended_Cost,
  NULL Opportunity,
  NULL SPR,
  OZF.ATTRIBUTE7 End_User,
  NULL POS_INV_DATE,
  OZF.ATTRIBUTE15 SEQ_NUMBER
FROM OZF_SALES_TRANSACTIONS_ALL OZF,
  HZ_PARTIES HP,
  HZ_CUST_ACCOUNTS HZC,
  MTL_SYSTEM_ITEMS_B MTL
WHERE OZF.SOURCE_CODE     = 'MA'
--AND OZF.transfer_type     = 'IN'
AND OZF.SOLD_TO_PARTY_ID=HP.PARTY_ID  
AND OZF.INVENTORY_ITEM_ID =MTL.INVENTORY_ITEM_ID 
AND HP.PARTY_ID           = HZC.PARTY_ID
AND HZC.SALES_CHANNEL_CODE ='CHANNEL_PARTNER'
AND MTL.ORGANIZATION_ID   =fnd_profile.value('AMS_ITEM_ORGANIZATION_ID')
and  NOT EXISTS (Select REPLACE(LINE_ATTRIBUTE15,'-H','') from OZF_RESALE_LINES_INT_ALL where LINE_ATTRIBUTE15 like '%-H'  and quantity > 0
AND REPLACE(LINE_ATTRIBUTE15,'-H','')=OZF.ATTRIBUTE15)
AND  NOT EXISTS
(SELECT LINE_ATTRIBUTE15
FROM OZF_RESALE_LINES_INT_ALL
WHERE LINE_ATTRIBUTE15 NOT LIKE '%-H'
AND line_attribute14 IS NULL
AND LINE_ATTRIBUTE15=OZF.ATTRIBUTE5
AND item_number       = 'COTERM'
);
